### ISSUE TITLE
Firefox plugin

### ISSUE THREAD

**Issue by lrustand** [NicTorgersen/skakkehanopluss-chrome#1]
Jeg synes dette er en veldig bra plugin og har brukt den i flere år. Men har gått over til å bruke firefox og lurte på om det er mulig å få en versjon til firefox også :)

**Comment by NicTorgersen** [comment]
Hei, dette er faktisk på vei! Takk for at du viser interesse 💃

**Comment by NicTorgersen** [comment]
Utvidelsen er nå postet til [addons.mozilla.org](https://addons.mozilla.org/en-US/firefox/addon/ska-kke-ha-no-pluss/)

**Comment by lrustand** [comment]
Tusen takk!

**Comment by lrustand** [comment]
Hei, jeg prøvde å installere pluginen fra mozilla.org nå, men så får jeg feilmelding av firefox: "Klarte ikke laste ned utvidelsen fordi det ser ut som den er skadet."

**Comment by NicTorgersen** [comment]
Den ligger ute til godkjenning, ca nummer 100 i køen (var 120 da jeg la den ut i går kveld) så det kan ta litt tid før du får benyttet den. Repoet ligger på [skakkehanopluss-firefox](https://github.com/NicTorgersen/skakkehanopluss-firefox), så hvis du er kjempeinteressert kan du laste ned repoet og laste inn utvidelsen i debug-modus.

**Comment by NicTorgersen** [comment]
Da har jeg fått litt tyn fra mozilla ang. noen småting. Burde være fikset og utvidelsen vil ligge på mozilla-store om kort tid 👍
